# -*- coding: utf-8 -*-
"""Entregable parte 2- ej1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WI9Jn_hAr1ZU436U4XN2j-eKTov5XkUg
"""

import io
import matplotlib
import matplotlib.pyplot as plt
import numpy
import pandas as pd
import seaborn

seaborn.set_context('talk')

"""## Lectura del dataset

En la notebook 00 se explican los detalles de la siguiente sección.
"""

url = 'https://cs.famaf.unc.edu.ar/~mteruel/datasets/diplodatos/sysarmy_survey_2020_processed.csv'
df = pd.read_csv(url)

df[:3]

df[['profile_gender', 'salary_monthly_NETO']].groupby('profile_gender').describe()

df[df.salary_monthly_NETO > 1000]\
  [['profile_gender', 'salary_monthly_NETO']].groupby('profile_gender').describe()

alpha = 0.05

is_man = df.profile_gender == 'Hombre'

groupA = df[(df.salary_monthly_NETO > 1000) & is_man].salary_monthly_NETO
groupB = df[(df.salary_monthly_NETO > 1000) & ~is_man].salary_monthly_NETO

seaborn.histplot(groupA, bins=50)

seaborn.histplot(groupB, bins=50)

"""## Ejercicio 1: Estimación

**Consigna:**  Calcular una estimación puntual y un intervalo de confianza de nivel (1-alpha) para la resta entre la media del salario Neto para Hombres menos la media del salario Neto para otros géneros(diferencia de las medias entre el grupoA y grupoB). 
¿Cómo se relaciona este intervalo de confianza con el test de hipótesis?

estimación puntual para la resta entre la media del salario Neto para Hombres menos la media del salario Neto para otros géneros(diferencia de las medias entre el grupoA y grupoB)
"""

#El parámetro a estimar es la diferencia de medias. Se calculan las medias de los dos grupos de variables y
#luego se efectua la resta
media_grupoA = groupA.mean()
media_grupoB = groupB.mean()

print(media_grupoA)
print(media_grupoB)

dif_medias_grupoAB = media_grupoA - media_grupoB
dif_medias_grupoAB

std_grupoA = groupA.std()
std_grupoB = groupB.std()

print(std_grupoA)
print(std_grupoB)

len(groupA)

len(groupB)

#se genera una muestra del grupo A, para luego calcular el Estadístico.
#en este supuesto se utilizará el Estadśitico Media Muestral

n_A = 2000
#generamos muestra del grupo A
muestra_grupoA=groupA.sample(n_A, replace=False) # muestra de tamaño n

seaborn.histplot(muestra_grupoA, bins=50)

#se calcula el estadistico para la muestra del grupo A

#estimador media muestral grupo A
promedio_muestraA = muestra_grupoA.mean()
promedio_muestraA

#se genera una muestra del grupo B, para luego calcular el Estadístico.

#muestra grupo B
n_B=700
muestra_grupoB=groupB.sample(n_B, replace=False) # muestra de tamaño n

seaborn.histplot(muestra_grupoB, bins=30)

#se calcula el estadistico para la muestra del grupo B

#estimador media muestral grupo B
promedio_muestraB = muestra_grupoB.mean()
promedio_muestraB

print(muestra_grupoA.mean())
print(muestra_grupoB.mean())

#calculados los estadísticos de cada grupo, se procede a calcular la Estimación Puntual
#para el parámetro diferencia de medias


#estimación puntual 
dif_medias_muestraAB = muestra_grupoA.mean()-muestra_grupoB.mean()
dif_medias_muestraAB

"""intervalo de confianza de nivel (1-alpha) para la resta entre la media del salario Neto para Hombres menos la media del salario Neto para otros géneros(diferencia de las medias entre el grupoA y grupoB)"""

#se calculan las varianzas de las muestras para determinar cómo calcular el estadístico pivote

print(muestra_grupoA.var())
print(muestra_grupoB.var())

grados_de_libertad = ((muestra_grupoA.std()/n_A+muestra_grupoB.std()/n_B)**2)/(((muestra_grupoA.std()/n_A)**2)/n_A-1+((muestra_grupoB.std()/n_B)**2)/n_B-1)
grados_de_libertad

std_A=muestra_grupoA.std()
std_B=muestra_grupoB.std()

#para calcular el intervalo de confianza de nivel 1-alpha para diferencia de medias
#se aplica el método Weltch ya que las muestras tienen varianza diferente,
# El método que utiliza t de student para el calculo de los intervalos Inferior y Superior

#El nivel del intervalo es de 1-0.05=0.95
alpha = 0.05
t_score = 1.96

#se calculan los intervalos
estadistico_liminf =(promedio_muestraA-promedio_muestraB)-t_score*numpy.sqrt(std_A/n_A+std_B/n_B)
estadistico_limsup =(promedio_muestraA-promedio_muestraB)+t_score*numpy.sqrt(std_A/n_A+std_B/n_B)

long_intervalo =estadistico_limsup-estadistico_liminf
long_intervalo

"""¿Cómo se relaciona este intervalo de confianza con el test de hipótesis?"""

#Este intervalo de confianza de nivel 0.95, sirve para confirmar o rechazar la hipotesis nula
#que se plantee en el test de hipótesis.
#Del intervalo de confianza de nivel 0.95 se deduce que la probabilidad de que el parámetro a estimar
#se ubique dentro de de los límites del intérvalo es del 95%, y solo en un 5% de casos el parámetro quedará por fuera del intervalo